### ISSUE TITLE
Program unusable when having more than one physical monitor

### ISSUE THREAD

**Issue by dexamenos** [scottaxcell/winddcutil#10]
```
C:\Program Files\<some-folder>\vesa-utils>winddcutil.exe detect
Traceback (most recent call last):
  File "cli.py", line 6, in <module>
  File "winddcutil\__main__.py", line 10, in main
  File "winddcutil\winddcutil.py", line 10, in detect
  File "monitorcontrol\monitorcontrol.py", line 84, in __enter__
  File "monitorcontrol\vcp\vcp_windows.py", line 55, in __enter__
monitorcontrol.vcp.vcp_abc.VCPError: more than one physical monitor per hmonitor
[3636] Failed to execute script 'cli' due to unhandled exception!
```

I have two physical monitors (Desktop + Beamer), both showing the same desktop (duplicate).

**Comment by Reginald-Gillespie** [comment]
Are you sure this is due to having two external monitors and not due to the monitor for some reason having embedded virtual registered inside of it? A friend accidentally lock his monitor (that does not have a power button) off and had this error when attempting to turn it back on (so I'm just trying to figure out what caused it).

**Comment by dexamenos** [comment]
@Reginald-Gillespie: I am not very familiar with how those physical and virtual monitors are organised within Windows. The only thing I can check is: when only the desktop monitor is attached / physically plugged in, everything works. As soon as I plug in the Beamer, the behaviour depends: if I mirror the desktop contents (so desktop and beamer showing the same picture), I receive the error above, but, if I extend the desktop to the beamer, everything works again.

**Comment by scottaxcell** [comment]
Issue filed by OP with the library with the source of the error. See https://github.com/newAM/monitorcontrol/issues/300.
